name = "zeptomail"
version = "2.1.0"

licences = ["Apache-2.0"]
description = "A wrapper for ZeptoMail's transactional email API"
repository = { type = "github", user = "lpil", repo = "zeptomail" }
links = [
  { title = "Website", href = "https://www.zoho.com/zeptomail/" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 4.0.0"
gleam_http = ">= 3.6.0 and < 5.0.0"

[dev-dependencies]
gleam_hackney = ">= 1.0.0 and < 2.0.0"
